#!/usr/bin/bash

if [ $# = 0 ]; then
  echo "Provide the asciidoc filename as input..."
else
  asciidoctor --backend docbook -a leveloffset=+1 --attribute=product-title="OpenShift Container Platform" --out-file - $1| pandoc --from docbook --to docx --output $1.docx
  gdrive import $1.docx | grep -oP "([A-Za-z0-9\-_]+[\d@]+[\w@]*|[\d@]+[A-Za-z0-9\-_]+[\w@]+[\-]*)" |
  echo "Your gdoc is available at https://docs.google.com/document/d/$(</dev/stdin)"
  rm $1.docx
fi
